name: PHP Composer

on: [push]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: install php
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          extensions: mbstring, intl
      - uses: actions/checkout@v1
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: php unit tests
        run: composer run-script test
